 * Serving Flask app "flask_server" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
Traceback (most recent call last):
  File "/Users/user/opt/anaconda3/lib/python3.8/socket.py", line 756, in getfqdn
    hostname, aliases, ipaddrs = gethostbyaddr(name)
socket.gaierror: [Errno 8] nodename nor servname provided, or not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "flask_server.py", line 30, in <module>
    app.run(host='0.0.0.0', port=2431, threaded=False)
  File "/Users/user/opt/anaconda3/lib/python3.8/site-packages/flask/app.py", line 990, in run
    run_simple(host, port, self, **options)
  File "/Users/user/opt/anaconda3/lib/python3.8/site-packages/werkzeug/serving.py", line 1052, in run_simple
    inner()
  File "/Users/user/opt/anaconda3/lib/python3.8/site-packages/werkzeug/serving.py", line 996, in inner
    srv = make_server(
  File "/Users/user/opt/anaconda3/lib/python3.8/site-packages/werkzeug/serving.py", line 862, in make_server
    return BaseWSGIServer(
  File "/Users/user/opt/anaconda3/lib/python3.8/site-packages/werkzeug/serving.py", line 740, in __init__
    HTTPServer.__init__(self, server_address, handler)
  File "/Users/user/opt/anaconda3/lib/python3.8/socketserver.py", line 452, in __init__
    self.server_bind()
  File "/Users/user/opt/anaconda3/lib/python3.8/http/server.py", line 140, in server_bind
    self.server_name = socket.getfqdn(host)
  File "/Users/user/opt/anaconda3/lib/python3.8/socket.py", line 756, in getfqdn
    hostname, aliases, ipaddrs = gethostbyaddr(name)
KeyboardInterrupt
